name:                url-shortener
version:             0.1.0.0
github:              "SVDerevyagin/url-shortener"
license:             BSD-3-Clause
author:              "SVDerevyagin"
maintainer:          "SVDerevyagin@gmail.com"
copyright:           "2026 SVDerevyagin"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SVDerevyagin/url-shortener#readme>

dependencies:
- base >= 4.7 && < 5
- hasql < 1.10
- hasql-th <0.5
- hedis
- mtl
- time
- bytestring
- vector
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  url-shortener:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - url-shortener
    - scotty
    - wai
    - aeson
    - text

  urlsh:
    main:                Main.hs
    source-dirs:         cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - url-shortener
    - optparse-applicative

tests:
  url-shortener-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - url-shortener
    - hspec
    - QuickCheck
